// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddWarehouse(ctx context.Context, arg AddWarehouseParams) (WarehouseWarehouse, error)
	AddWarehouseRack(ctx context.Context, arg AddWarehouseRackParams) (WarehouseWarehouseRack, error)
	GetRack(ctx context.Context, id string) (GetRackRow, error)
	GetRacks(ctx context.Context, arg GetRacksParams) ([]GetRacksRow, error)
	GetWarehouseRacks(ctx context.Context, warehouseID string) ([]GetWarehouseRacksRow, error)
	GetWarehouses(ctx context.Context, arg GetWarehousesParams) ([]WarehouseWarehouse, error)
	UpsertRack(ctx context.Context, arg UpsertRackParams) (WarehouseRack, error)
}

var _ Querier = (*Queries)(nil)
